language: php

addons:
  apt:
    packages:
      - ant

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

services:
  - mysql

env:
  matrix:
    - SHOPWARE_VERSION="6.1"
    - SHOPWARE_VERSION="6.2"
  global:
    - PLUGIN_NAME=WbmTagManagerEcomm
    - SHOPWARE_DIRECTORY=${HOME}/shopware
    - PLUGIN_DIRECTORY=${SHOPWARE_DIRECTORY}/custom/plugins

cache:
  directories:
    - ${HOME}/.composer/cache/files

install:
  - composer install

before_script:
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
  - git clone https://github.com/shopware/platform.git ${SHOPWARE_DIRECTORY} --branch ${SHOPWARE_VERSION}
  - cd ${SHOPWARE_DIRECTORY}
  - echo APP_ENV=prod >> .env
  - echo APP_SECRET=8583a6ff63c5894a3195331701749943 >> .env
  - echo APP_URL=http://localhost >> .env
  - echo DATABASE_URL=mysql://travis:@127.0.0.1:3306/shopware >> .env
  - composer install --no-dev --no-progress --no-suggest --ignore-platform-reqs
  - mv ${TRAVIS_BUILD_DIR} ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}
  - php ${HOPWARE_DIRECTORY}/bin/console plugin:refresh
  - php ${HOPWARE_DIRECTORY}/bin/console plugin:install -a ${PLUGIN_NAME}
  - cd ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}

script:
  - composer test

after_success:
  - ./build.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: WbmTagManagerEcomm*.zip
  on:
    tags: true
